set nocompatible    "required for Vundle
filetype off

let isWindows = has('win32')

" set runtime path to include Vundle and initialize
if isWindows
    set rtp+=$HOME/vimfiles/bundle/Vundle.vim/
    call vundle#begin('$HOME/vimfiles/bundle/')
else
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
endif

Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'scrooloose/nerdtree'

"All Plugins must be added before following line
call vundle#end()

filetype plugin indent on
"To ignore plugin indent changes, use:
"filetype plugin on
"Help :
":PluginList    -lists configured plugins
":PluginInstall -installs plugins; append '!' to update or use :PluginUpdate
":PluginSearch foo -searches for foo; append '!' to refresh local cache
":PluginClean   -confirms removal of unused plugins; append '!' to autoapprove

"airline plugin
set laststatus=2    "show statusline
let g:airline_theme='luna'
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

" airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

set encoding=utf-8

set noerrorbells
set lazyredraw
set cursorline
set scrolloff=999
set number          "line numbers on
syntax enable
set showmatch       "highlight matching braces
highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%81v', 100)  "highlight 81st column

set tabstop=4       "tabs are 4 spaces wide
set shiftwidth=4
set expandtab


set list
set listchars=tab:\|┄,trail:♡,eol:¬

if has('gui_running')
    set gcr=a:blinkoff0
    set guifont=DejaVu\ Sans\ Mono\ for\ Powerline:h11
    set background=dark
    colorscheme solarized
else
    if isWindows
        colorscheme elflord "give up on cmd colors
    else
        set background dark
        colorscheme solarized
    endif
endif

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
inoremap jk <Esc>

set nobackup    "no swap and backup files
set noswapfile
set viminfo=
